### ISSUE TITLE
PG::ConnectionBad: connection is closed

### ISSUE THREAD

**Issue by yegor256** [yegor256/pgtk#21]
```
PG::ConnectionBad: connection is closed
  from pgtk/pool.rb:142:in `async_exec_params'
  from pgtk/pool.rb:142:in `exec'
  from pgtk/pool.rb:112:in `block in exec'
  from pgtk/pool.rb:166:in `connect'
  from pgtk/pool.rb:105:in `exec'
  from objects/pipeline.rb:42:in `fetch'
  from mailanes.rb:124:in `block (3 levels) in <top (required)>'
  from mailanes.rb:120:in `loop'
  from mailanes.rb:120:in `block (2 levels) in <top (required)>'
PG::ConnectionBad: connection is closed
  from pgtk/pool.rb:168:in `finish'
  from pgtk/pool.rb:168:in `rescue in connect'
  from pgtk/pool.rb:167:in `connect'
  from pgtk/pool.rb:105:in `exec'
  from objects/pipeline.rb:42:in `fetch'
  from mailanes.rb:124:in `block (3 levels) in <top (required)>'
  from mailanes.rb:120:in `loop'
  from mailanes.rb:120:in `block (2 levels) in <top (required)>'
```

**Comment by yegor256** [comment]
@rultor release tag is `0.7.5`

**Comment by 0crat** [comment]
Job `gh:yegor256/pgtk#21` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
